development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dnsadmin_dev
  pool: 5
  username: dnsadmin
  password: 3zcupuNpFdb2bdcH
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dnsadmin_test
  pool: 5
  username: dnsadmin
  password: 3zcupuNpFdb2bdcH
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dnsadmin
  pool: 5
  username: dnsadmin
  password: 3zcupuNpFdb2bdcH
  socket: /tmp/mysql.sock
